[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
boards_on_solana = "7Yq2LTPkk2ZidFkZ8gX9Nv56nGUQC7TmkHYk59pXAS7q"

[programs.devnet]
boards_on_solana = "7Yq2LTPkk2ZidFkZ8gX9Nv56nGUQC7TmkHYk59pXAS7q"

[programs.mainnet]
boards_on_solana = "7Yq2LTPkk2ZidFkZ8gX9Nv56nGUQC7TmkHYk59pXAS7q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
